import { useState, useEffect, memo, useCallback } from 'react';
import { useCiclo } from '../../contexts/CicloContext';
import { useToast } from '../../contexts/ToastContext';
import { formatMonto } from '../../utils/formatters';
import { getResumenFinanzas, getResumenMensual, getEgresos, getRecibos } from '../../api/endpoints';
import type { PaginatedResponse, Recibo, Egreso } from '../../api/endpoints';

interface ResumenFinanzas { ciclo: string; balance: { total_ingresos: number; total_egresos: number; ganancia_neta: number; porcentaje_egresos: number; porcentaje_ganancia: number; ticket_promedio: number }; ingresos: { recibos_pagados: number; num_recibos: number }; egresos: { gasto_taller: number; gasto_personal: number }; }
interface ResumenMensualItem { año: number; mes: number; nombre: string; ingresos: number; egresos: number; balance: number; recibos: number }
const PAGE_SIZE = 20;

/**
 * FinanzasPage — Resumen financiero del ciclo activo
 *
 * Vista con cuatro pestañas (tabs):
 *   1. Resumen: tarjetas de ingresos, ganancia neta (con toggle mostrar/ocultar), egresos,
 *      y métricas derivadas (ticket promedio, ratio de egresos, margen neto)
 *   2. Mensual: tabla con desglose por mes (ingresos vs egresos, balance)
 *   3. Ingresos: tabla paginada de recibos con estado "pagado"
 *   4. Egresos: tabla paginada con todos los egresos del ciclo
 *
 * La ganancia neta se oculta por defecto (privacidad); el toggle showGanancia
 * reemplaza "••••••" por el monto real.
 */
const FinanzasPage = memo(function FinanzasPage() {
  const { cicloActual } = useCiclo(); const { showToast } = useToast();
  const [activeTab, setActiveTab] = useState<'resumen'|'mensual'|'ingresos'|'egresos'>('resumen');
  const [finanzas, setFinanzas] = useState<ResumenFinanzas|null>(null); const [resumenMensual, setResumenMensual] = useState<ResumenMensualItem[]>([]);
  const [loading, setLoading] = useState(true); const [showGanancia, setShowGanancia] = useState(false);
  const [ingresos, setIngresos] = useState<Recibo[]>([]); const [ingresosPage, setIngresosPage] = useState(1); const [ingresosTotal, setIngresosTotal] = useState(0); const [ingresosPages, setIngresosPages] = useState(1); const [ingresosLoading, setIngresosLoading] = useState(false);
  const [egresosTab, setEgresosTab] = useState<Egreso[]>([]); const [egresosPage, setEgresosPage] = useState(1); const [egresosTotal, setEgresosTotal] = useState(0); const [egresosPages, setEgresosPages] = useState(1); const [egresosLoading, setEgresosLoading] = useState(false);

  const loadResumen = useCallback(async () => { if(!cicloActual)return; setLoading(true); try { const[f,m]=await Promise.all([getResumenFinanzas(cicloActual.id),getResumenMensual(cicloActual.id)]); setFinanzas(f.data); setResumenMensual(m.data); } catch{showToast('Error al cargar resumen','error')} finally{setLoading(false)} },[cicloActual,showToast]);
  useEffect(()=>{if(cicloActual)loadResumen()},[cicloActual,loadResumen]);

  const fetchIngresos = useCallback(async(page=1)=>{if(!cicloActual)return;setIngresosLoading(true);try{const r=await getRecibos(cicloActual.id,`estado=pagado&page=${page}`);const d:PaginatedResponse<Recibo>=r.data;setIngresos(d.results);setIngresosTotal(d.count);setIngresosPages(Math.ceil(d.count/PAGE_SIZE)||1);setIngresosPage(page)}catch{showToast('Error al cargar ingresos','error')}finally{setIngresosLoading(false)}},[cicloActual,showToast]);
  const fetchEgresos = useCallback(async(page=1)=>{if(!cicloActual)return;setEgresosLoading(true);try{const r=await getEgresos(cicloActual.id,`page=${page}`);const d:PaginatedResponse<Egreso>=r.data;setEgresosTab(d.results);setEgresosTotal(d.count);setEgresosPages(Math.ceil(d.count/PAGE_SIZE)||1);setEgresosPage(page)}catch{showToast('Error al cargar egresos','error')}finally{setEgresosLoading(false)}},[cicloActual,showToast]);
  useEffect(()=>{if(activeTab==='ingresos'&&ingresos.length===0)fetchIngresos(1);if(activeTab==='egresos'&&egresosTab.length===0)fetchEgresos(1)},[activeTab]);

  if(!cicloActual)return null;
  if(loading)return <div style={{display:'flex',justifyContent:'center',alignItems:'center',minHeight:'60vh',color:'#6b7280',fontSize:'0.9375rem'}}>Cargando resumen financiero...</div>;

  // Tabs: cada pestaña tiene su propia lógica de carga de datos
  const tabs = [{id:'resumen',label:'Resumen'},{id:'mensual',label:'Mensual'},{id:'ingresos',label:'Ingresos'},{id:'egresos',label:'Egresos'}] as const;

  return (<div style={{maxWidth:'1100px',margin:'0 auto'}}>
    <div style={{marginBottom:'1.75rem'}}><div style={{display:'flex',alignItems:'baseline',gap:'0.75rem',flexWrap:'wrap'}}><h1 style={{fontSize:'1.625rem',fontWeight:700,color:'#0f172a',margin:0,letterSpacing:'-0.02em'}}>Finanzas</h1><span style={{fontSize:'0.75rem',fontWeight:500,color:'#b59410',background:'#fef9e7',padding:'0.2rem 0.65rem',borderRadius:'9999px'}}>{cicloActual.nombre}</span><button onClick={()=>setShowGanancia(v=>!v)} title={showGanancia?'Ocultar':'Mostrar'} className="touch-target" style={{marginLeft:'auto',padding:'0.35rem 0.65rem',border:'1px solid #e5e7eb',borderRadius:'8px',background:'white',cursor:'pointer',fontSize:'0.75rem',color:'#6b7280',display:'flex',alignItems:'center',gap:'0.35rem',minHeight:'36px'}}><span style={{fontSize:'1rem',lineHeight:1}}>{showGanancia?'👁':'👁‍🗨'}</span>{showGanancia?'Ocultar':'Mostrar'}</button></div><div style={{height:3,width:48,background:'linear-gradient(90deg,#d4af37,#f0d878)',borderRadius:2,marginTop:'0.5rem'}}/></div>
    <div style={{display:'flex',gap:'0.25rem',marginBottom:'1.75rem',borderBottom:'1.5px solid #e5e7eb'}}>{tabs.map(t=>(<button key={t.id} onClick={()=>setActiveTab(t.id)} className="touch-target" style={{padding:'0.625rem 1.125rem',minHeight:'44px',background:'none',border:'none',borderBottom:activeTab===t.id?'2px solid #d4af37':'2px solid transparent',color:activeTab===t.id?'#0f172a':'#6b7280',fontWeight:activeTab===t.id?600:400,fontSize:'0.875rem',cursor:'pointer',marginBottom:'-1.5px',transition:'color 0.15s,border-color 0.15s'}}>{t.label}</button>))}</div>

    {activeTab==='resumen'&&finanzas&&(<>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1.5fr 1fr',gap:'0.875rem',marginBottom:'1.25rem'}}>
        <CardBalance label="Ingresos" value={finanzas.balance.total_ingresos} variant="green"/>
        <div style={{background:'linear-gradient(135deg,#1e1b2e,#2d2340,#1a1625)',borderRadius:'14px',padding:'1.5rem 1.75rem',display:'flex',flexDirection:'column',justifyContent:'center',alignItems:'center',border:'1px solid rgba(212,175,55,0.25)'}}>
          <span style={{fontSize:'0.6875rem',fontWeight:600,color:'#d4af37',textTransform:'uppercase',letterSpacing:'0.08em',marginBottom:'0.375rem'}}>Ganancia Neta</span>
          <span style={{fontSize:'2.25rem',fontWeight:800,color:'#f0d878',letterSpacing:showGanancia?'-0.02em':'0.12em',lineHeight:1.15,transition:'letter-spacing 0.2s'}}>{showGanancia?formatMonto(finanzas.balance.ganancia_neta):'••••••'}</span>
          {showGanancia&&<span style={{fontSize:'0.75rem',color:finanzas.balance.ganancia_neta>=0?'#34d399':'#f87171',marginTop:'0.25rem',fontWeight:500}}>{finanzas.balance.porcentaje_ganancia.toFixed(1)}% del ingreso</span>}
        </div>
        <CardBalance label="Egresos" value={finanzas.balance.total_egresos} variant="red"/>
      </div>
      <div style={{display:'flex',gap:0,marginBottom:'1.5rem',background:'white',borderRadius:'12px',boxShadow:'0 1px 4px rgba(0,0,0,0.04)',border:'1px solid #f3f4f6',overflow:'hidden'}}>
        {[{label:'Recibos emitidos',value:finanzas.ingresos.num_recibos??0},{label:'Ticket promedio',value:formatMonto(finanzas.balance.ticket_promedio)},{label:'Ratio egresos',value:`${finanzas.balance.porcentaje_egresos.toFixed(1)}%`},{label:'Margen neto',value:showGanancia?`${finanzas.balance.porcentaje_ganancia.toFixed(1)}%`:'••••'}].map((m,i)=>(<div key={m.label} style={{flex:1,textAlign:'center',padding:'1rem 0.75rem',borderRight:i<3?'1px solid #f3f4f6':'none'}}><div style={{fontSize:'0.6875rem',color:'#9ca3af',textTransform:'uppercase',letterSpacing:'0.04em',marginBottom:'0.25rem'}}>{m.label}</div><div style={{fontSize:'1.125rem',fontWeight:700,color:'#1f2937'}}>{m.value}</div></div>))}
      </div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:'1rem'}}>
        <div style={{background:'white',borderRadius:'12px',padding:'1.25rem 1.5rem',boxShadow:'0 1px 4px rgba(0,0,0,0.04)',border:'1px solid #f3f4f6'}}><div style={{display:'flex',alignItems:'center',gap:'0.5rem',marginBottom:'1rem'}}><span style={{width:8,height:8,borderRadius:'50%',background:'#22c55e',flexShrink:0}}/><h3 style={{fontSize:'0.8125rem',fontWeight:600,color:'#1f2937',margin:0,textTransform:'uppercase',letterSpacing:'0.04em'}}>Ingresos</h3></div><div style={{display:'flex',justifyContent:'space-between',alignItems:'baseline',padding:'0.5rem 0'}}><span style={{color:'#6b7280',fontSize:'0.8125rem'}}>Recibos pagados</span><span style={{fontWeight:700,color:'#059669',fontSize:'1rem'}}>{formatMonto(finanzas.ingresos.recibos_pagados)}</span></div></div>
        <div style={{background:'white',borderRadius:'12px',padding:'1.25rem 1.5rem',boxShadow:'0 1px 4px rgba(0,0,0,0.04)',border:'1px solid #f3f4f6'}}><div style={{display:'flex',alignItems:'center',gap:'0.5rem',marginBottom:'1rem'}}><span style={{width:8,height:8,borderRadius:'50%',background:'#ef4444',flexShrink:0}}/><h3 style={{fontSize:'0.8125rem',fontWeight:600,color:'#1f2937',margin:0,textTransform:'uppercase',letterSpacing:'0.04em'}}>Egresos</h3></div>{[{label:'Gastos del taller',value:finanzas.egresos.gasto_taller},{label:'Pago a profesores',value:finanzas.egresos.gasto_personal}].map(e=>(<div key={e.label} style={{display:'flex',justifyContent:'space-between',padding:'0.4rem 0',borderBottom:'1px solid #f9fafb'}}><span style={{color:'#6b7280',fontSize:'0.8125rem'}}>{e.label}</span><span style={{fontWeight:600,color:'#dc2626',fontSize:'0.875rem'}}>{formatMonto(e.value)}</span></div>))}<div style={{display:'flex',justifyContent:'space-between',padding:'0.5rem 0 0 0',marginTop:'0.5rem',borderTop:'1.5px solid #f3f4f6'}}><span style={{fontWeight:600,color:'#991b1b',fontSize:'0.8125rem'}}>Total</span><span style={{fontWeight:700,color:'#dc2626',fontSize:'1rem'}}>{formatMonto(finanzas.balance.total_egresos)}</span></div></div>
      </div>
    </>)}

    {activeTab==='mensual'&&<TablaEstilizada columns={[{key:'nombre',label:'Mes',align:'left'},{key:'recibos',label:'Recibos',align:'right'},{key:'ingresos',label:'Ingresos',align:'right',format:formatMonto,color:'#059669'},{key:'egresos',label:'Egresos',align:'right',format:formatMonto,color:'#dc2626'},{key:'balance',label:'Balance',align:'right',format:formatMonto,bold:true,colorFn:(v:number)=>v>=0?'#059669':'#dc2626'}]} data={resumenMensual} keyField={item=>`${item.año}-${item.mes}`} emptyMsg="No hay datos mensuales" footer={resumenMensual.length>0?{nombre:'Total',recibos:resumenMensual.reduce((s,m)=>s+m.recibos,0),ingresos:resumenMensual.reduce((s,m)=>s+m.ingresos,0),egresos:resumenMensual.reduce((s,m)=>s+m.egresos,0),balance:resumenMensual.reduce((s,m)=>s+m.balance,0)}:undefined}/>}

    {activeTab==='ingresos'&&<PaginatedTable columns={['N°','Alumno','Monto','Fecha']} loading={ingresosLoading} page={ingresosPage} totalPages={ingresosPages} total={ingresosTotal} onPageChange={fetchIngresos} emptyMsg="No hay recibos pagados" rows={ingresos.map(r=>[<span style={{fontWeight:500}}>#{r.numero}</span>,r.alumno_nombre??<span style={{color:'#9ca3af'}}>—</span>,<span style={{fontWeight:600,color:'#059669'}}>{formatMonto(r.monto_pagado)}</span>,<span style={{color:'#6b7280',fontSize:'0.8125rem'}}>{new Date(r.fecha_emision).toLocaleDateString('es-PE',{day:'numeric',month:'short',year:'numeric'})}</span>])}/>}

    {activeTab==='egresos'&&<PaginatedTable columns={['Tipo','Monto','Descripción','Beneficiario','Fecha','Estado']} loading={egresosLoading} page={egresosPage} totalPages={egresosPages} total={egresosTotal} onPageChange={fetchEgresos} emptyMsg="No hay egresos" minWidth={720} rows={egresosTab.map(e=>[<TipoBadge tipo={e.tipo}/>,<span style={{fontWeight:600,color:'#dc2626'}}>{formatMonto(e.monto)}</span>,<span style={{color:'#6b7280',maxWidth:'200px',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'} as React.CSSProperties}>{e.descripcion||'—'}</span>,e.beneficiario||e.profesor_nombre||'—',<span style={{color:'#6b7280',fontSize:'0.8125rem'}}>{new Date(e.fecha).toLocaleDateString('es-PE',{day:'numeric',month:'short',year:'numeric'})}</span>,<EstadoBadge estado={e.estado}/>])}/>}
  </div>);
});

function CardBalance({label,value,variant}:{label:string;value:number;variant:'green'|'red'}){const c=variant==='green'?'#059669':'#dc2626';const bg=variant==='green'?'#ecfdf5':'#fef2f2';const b=variant==='green'?'rgba(16,185,129,0.15)':'rgba(220,38,38,0.15)';return<div style={{background:bg,borderRadius:'14px',padding:'1.5rem',border:`1px solid ${b}`,display:'flex',flexDirection:'column',justifyContent:'center'}}><span style={{fontSize:'0.6875rem',fontWeight:600,color:c,textTransform:'uppercase',letterSpacing:'0.06em',marginBottom:'0.375rem'}}>Total {label}</span><span style={{fontSize:'1.75rem',fontWeight:700,color:c,letterSpacing:'-0.02em',lineHeight:1.2}}>{formatMonto(value)}</span></div>}

function TipoBadge({tipo}:{tipo:string}){const ip=tipo==='gasto_personal'||tipo==='pago_profesor';return<span style={{padding:'0.2rem 0.55rem',borderRadius:'5px',fontSize:'0.75rem',fontWeight:500,background:ip?'#fef2f2':'#fefce8',color:ip?'#dc2626':'#ca8a04',whiteSpace:'nowrap'}}>{ip?'Profesor':'Taller'}</span>}
function EstadoBadge({estado}:{estado:string}){const ic=estado==='cancelado';return<span style={{padding:'0.2rem 0.55rem',borderRadius:'5px',fontSize:'0.75rem',fontWeight:500,whiteSpace:'nowrap',background:ic?'#ecfdf5':'#fef3c7',color:ic?'#059669':'#d97706'}}>{ic?'Cancelado':'Pendiente'}</span>}

function TablaEstilizada<T extends Record<string,any>>({columns,data,keyField,emptyMsg,footer}:{columns:{key:string;label:string;align:'left'|'right';format?:(v:any)=>string;color?:string;bold?:boolean;colorFn?:(v:any)=>string}[];data:T[];keyField:(item:T)=>string;emptyMsg:string;footer?:Record<string,any>}){return<div style={{background:'white',borderRadius:'12px',boxShadow:'0 1px 4px rgba(0,0,0,0.04)',border:'1px solid #f3f4f6',overflow:'hidden'}}><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr style={{background:'#f8fafc',borderBottom:'1.5px solid #e5e7eb'}}>{columns.map(c=><th key={c.key} style={{padding:'0.625rem 1rem',textAlign:c.align,fontSize:'0.6875rem',fontWeight:600,color:'#94a3b8',textTransform:'uppercase',letterSpacing:'0.05em'}}>{c.label}</th>)}</tr></thead><tbody>{data.length===0?<tr><td colSpan={columns.length} style={{padding:'3rem 1rem',textAlign:'center',color:'#9ca3af'}}>{emptyMsg}</td></tr>:data.map(item=>(<tr key={keyField(item)} style={{borderBottom:'1px solid #f3f4f6',transition:'background 0.1s'}} onMouseEnter={e=>e.currentTarget.style.background='#fafafa'} onMouseLeave={e=>e.currentTarget.style.background=''}>{columns.map(c=>{const raw=item[c.key];const color=c.colorFn?c.colorFn(raw):c.color;const display=c.format?c.format(raw):raw;return<td key={c.key} style={{padding:'0.625rem 1rem',textAlign:c.align,fontSize:'0.8125rem',fontWeight:c.bold?600:400,color:color??'#1f2937'}}>{display}</td>})}</tr>))}</tbody>{footer&&<tfoot><tr style={{background:'#f8fafc',borderTop:'1.5px solid #e5e7eb'}}>{columns.map(c=>{const raw=footer[c.key];const display=c.format?c.format(raw):raw;return<td key={c.key} style={{padding:'0.625rem 1rem',textAlign:c.align,fontSize:'0.875rem',fontWeight:700,color:c.color??'#0f172a'}}>{display}</td>})}</tr></tfoot>}</table></div></div>}

function PaginatedTable({columns,rows,loading,page,totalPages,total,onPageChange,emptyMsg,minWidth=600}:{columns:string[];rows:React.ReactNode[][];loading:boolean;page:number;totalPages:number;total:number;onPageChange:(p:number)=>void;emptyMsg:string;minWidth?:number}){return<div style={{background:'white',borderRadius:'12px',boxShadow:'0 1px 4px rgba(0,0,0,0.04)',border:'1px solid #f3f4f6',overflow:'hidden'}}><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth}}><thead><tr style={{background:'#f8fafc',borderBottom:'1.5px solid #e5e7eb'}}>{columns.map((c,i)=><th key={i} style={{padding:'0.625rem 1rem',textAlign:'left',fontSize:'0.6875rem',fontWeight:600,color:'#94a3b8',textTransform:'uppercase',letterSpacing:'0.05em'}}>{c}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={columns.length} style={{padding:'3rem 1rem',textAlign:'center',color:'#9ca3af'}}>Cargando...</td></tr>:rows.length===0?<tr><td colSpan={columns.length} style={{padding:'3rem 1rem',textAlign:'center',color:'#9ca3af'}}>{emptyMsg}</td></tr>:rows.map((row,i)=>(<tr key={i} style={{borderBottom:'1px solid #f3f4f6',transition:'background 0.1s'}} onMouseEnter={e=>e.currentTarget.style.background='#fafafa'} onMouseLeave={e=>e.currentTarget.style.background=''}>{row.map((cell,j)=><td key={j} style={{padding:'0.625rem 1rem',fontSize:'0.8125rem',color:'#1f2937'}}>{cell}</td>)}</tr>))}</tbody></table></div>{totalPages>1&&<div style={{display:'flex',justifyContent:'center',alignItems:'center',gap:'0.75rem',padding:'0.75rem 1rem',borderTop:'1px solid #f3f4f6',fontSize:'0.8125rem'}}><button disabled={page<=1} onClick={()=>onPageChange(page-1)} className="touch-target" style={{padding:'0.4rem 0.75rem',border:'1px solid #e5e7eb',borderRadius:'8px',background:'white',cursor:'pointer',fontSize:'0.8125rem',color:'#374151'}}>← Anterior</button><span style={{color:'#9ca3af'}}>Pág. {page} de {totalPages} ({total} reg.)</span><button disabled={page>=totalPages} onClick={()=>onPageChange(page+1)} className="touch-target" style={{padding:'0.4rem 0.75rem',border:'1px solid #e5e7eb',borderRadius:'8px',background:'white',cursor:'pointer',fontSize:'0.8125rem',color:'#374151'}}>Siguiente →</button></div>}</div>}
export default FinanzasPage;
