# Generated by Django 6.0.3 on 2026-03-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
