# Generated by Django 6.0.3 on 2026-03-28 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_fecha_nacimiento_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='es_recuperacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('asistio', 'Asistió'), ('falta', 'Falta'), ('falta_grave', 'Falta Grave')], default='asistio', max_length=20),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.matricula'),
        ),
    ]
