# Generated by Django 6.0.3 on 2026-03-28 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_update_asistencia_estados'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialTraspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_traspaso', models.DateTimeField(auto_now_add=True)),
                ('asistencias_transferidas', models.PositiveIntegerField(default=0)),
                ('alumno_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_destino', to='core.alumno')),
                ('alumno_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_origen', to='core.alumno')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos', to='core.ciclo')),
                ('matricula_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_destino', to='core.matricula')),
                ('matricula_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_origen', to='core.matricula')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos', to='core.taller')),
            ],
            options={
                'ordering': ['-fecha_traspaso'],
            },
        ),
    ]
