# Generated by Django 6.0.3 on 2026-03-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_historialtraspaso"),
    ]

    operations = [
        migrations.AddField(
            model_name="recibo",
            name="descuento",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Descuento aplicado",
            ),
        ),
        migrations.AddField(
            model_name="recibo",
            name="monto_bruto",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Monto Bruto (sin descuento)",
            ),
        ),
        migrations.AddField(
            model_name="recibo",
            name="paquete_aplicado",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("combo_musical_12", "Combo Musical 12+12"),
                    ("combo_musical_8", "Combo Musical 8+8"),
                    ("combo_musical_12_8", "Combo Musical 12+8"),
                    ("mixto_12", "Mixto 12+12"),
                    ("mixto_8", "Mixto 8+8"),
                    ("mixto_12_8", "Mixto 12+8"),
                    ("intensivo_instrumento", "Intensivo Instrumento"),
                    ("intensivo_taller", "Intensivo Taller"),
                ],
                default="individual",
                max_length=30,
                verbose_name="Paquete promocional aplicado",
            ),
        ),
        migrations.AddField(
            model_name="recibo",
            name="precio_editado",
            field=models.BooleanField(
                default=False, verbose_name="¿Precio fue editado manualmente?"
            ),
        ),
        migrations.AddField(
            model_name="taller",
            name="tipo",
            field=models.CharField(
                choices=[("instrumento", "Instrumento"), ("taller", "Taller")],
                default="taller",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.CreateModel(
            name="PrecioPaquete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_taller",
                    models.CharField(
                        choices=[("instrumento", "Instrumento"), ("taller", "Taller")],
                        max_length=20,
                        verbose_name="Tipo de Taller",
                    ),
                ),
                (
                    "tipo_paquete",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("combo_musical", "Combo Musical (2 Instrumentos)"),
                            ("mixto", "Mixto (Instrumento + Taller)"),
                            ("intensivo", "Intensivo"),
                        ],
                        default="individual",
                        max_length=20,
                        verbose_name="Tipo de Paquete",
                    ),
                ),
                (
                    "cantidad_clases",
                    models.IntegerField(
                        choices=[
                            (1, "Clase suelta"),
                            (8, "Paquete 8 clases"),
                            (12, "Paquete 12 clases"),
                            (20, "Paquete 20 clases"),
                        ],
                        verbose_name="Cantidad de Clases",
                    ),
                ),
                (
                    "precio_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio Total"
                    ),
                ),
                (
                    "precio_por_sesion",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Precio por Sesión",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Precio de Paquete",
                "verbose_name_plural": "Precios de Paquetes",
                "ordering": ["tipo_paquete", "tipo_taller", "cantidad_clases"],
                "unique_together": {("tipo_taller", "tipo_paquete", "cantidad_clases")},
            },
        ),
    ]
