# Generated by Django 6.0.3 on 2026-03-30 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_recibo_descuento_recibo_monto_bruto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recibo",
            name="alumno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recibos",
                to="core.alumno",
                verbose_name="Alumno principal (opcional)",
            ),
        ),
    ]
