# Generated by Django 6.0.3 on 2026-03-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_recibo_alumno"),
    ]

    operations = [
        migrations.AddField(
            model_name="matricula",
            name="metodo_pago",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("transferencia", "Transferencia"),
                    ("tarjeta", "Tarjeta"),
                    ("otro", "Otro"),
                ],
                default="efectivo",
                max_length=20,
            ),
        ),
    ]
