# Generated by Django 6.0.3 on 2026-03-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_matricula_metodo_pago"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="matricula",
            unique_together=set(),
        ),
    ]
