# Generated by Django 6.0.3 on 2026-03-30 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_matricula_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recibo",
            options={"ordering": ["-id"]},
        ),
        migrations.RemoveField(
            model_name="matricula",
            name="modalidad",
        ),
    ]
