# Generated by Django 6.0.3 on 2026-03-30 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_modalidad"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pagoprofesor",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="pagoprofesor",
            name="fecha_fin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pagoprofesor",
            name="fecha_inicio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pagoprofesor",
            name="ganancia_taller",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="pagoprofesor",
            name="total_alumnos_asistencias",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PagoProfesorDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("num_alumnos", models.PositiveIntegerField(default=0)),
                (
                    "valor_generado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "monto_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "monto_adicional",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "monto_profesor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ganancia_taller",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "horario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_detalle",
                        to="core.horario",
                    ),
                ),
                (
                    "pago_profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="core.pagoprofesor",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "horario__dia_semana", "horario__hora_inicio"],
                "unique_together": {("pago_profesor", "horario", "fecha")},
            },
        ),
    ]
