# Generated by Django 6.0.3 on 2026-04-02 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_pagoprofesor_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="preciopaquete",
            options={
                "ordering": ["ciclo", "tipo_paquete", "tipo_taller", "cantidad_clases"],
                "verbose_name": "Precio de Paquete",
                "verbose_name_plural": "Precios de Paquetes",
            },
        ),
        migrations.AlterUniqueTogether(
            name="preciopaquete",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="preciopaquete",
            name="ciclo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="precios_paquete",
                to="core.ciclo",
                verbose_name="Ciclo",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="preciopaquete",
            unique_together={
                ("ciclo", "tipo_taller", "tipo_paquete", "cantidad_clases")
            },
        ),
    ]
