# Generated by Django 6.0.3 on 2026-04-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_preciopaquete_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="preciopaquete",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="preciopaquete",
            name="cantidad_clases_secundaria",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Clase suelta"),
                    (8, "Paquete 8 clases"),
                    (12, "Paquete 12 clases"),
                    (20, "Paquete 20 clases"),
                ],
                help_text="Solo para combo_musical y mixto. Ej: combo 12+8 → principal=12, secundaria=8",
                null=True,
                verbose_name="Cantidad de Clases Secundaria",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="preciopaquete",
            unique_together={
                (
                    "ciclo",
                    "tipo_taller",
                    "tipo_paquete",
                    "cantidad_clases",
                    "cantidad_clases_secundaria",
                )
            },
        ),
    ]
