# Generated by Django 6.0.3 on 2026-04-03 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_horario_tipo_pago"),
    ]

    operations = [
        migrations.CreateModel(
            name="Egreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("gasto_taller", "Gasto del Taller"),
                            ("pago_profesor", "Pago a Profesor"),
                            ("gasto_personal", "Gasto de Personal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descripcion", models.CharField(blank=True, max_length=255)),
                ("fecha", models.DateField()),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("transferencia", "Transferencia"),
                            ("yape", "Yape"),
                            ("plin", "Plin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("categoria", models.CharField(blank=True, max_length=50)),
                ("beneficiario", models.CharField(blank=True, max_length=150)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="egresos",
                        to="core.ciclo",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="egresos",
                        to="core.profesor",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
    ]
