# Generated by Django 6.0.3 on 2026-04-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_egreso_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="egreso",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("gasto_taller", "Gasto del Taller"),
                    ("pago_profesor", "Pago a Profesor"),
                    ("gasto_personal", "Gasto de Personal"),
                ],
                max_length=20,
            ),
        ),
    ]
