# Generated by Django 6.0.3 on 2026-04-07 01:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_egreso_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracion",
            name="pago_dinamico_base",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("17.00"),
                max_digits=10,
                verbose_name="Base pago dinámico",
            ),
        ),
        migrations.AddField(
            model_name="configuracion",
            name="pago_dinamico_tope",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("35.00"),
                max_digits=10,
                verbose_name="Tope máximo pago dinámico",
            ),
        ),
    ]
