# Generated by Django 6.0.3 on 2026-04-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_agregar_campos_pago_dinamico_configuracion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asistencia",
            name="estado",
            field=models.CharField(
                choices=[
                    ("asistio", "Asistió"),
                    ("falta", "Falta"),
                    ("falta_grave", "Falta Grave"),
                ],
                db_index=True,
                default="asistio",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="fecha",
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="asistencia",
            index=models.Index(
                fields=["horario", "fecha"], name="asistencia_horario_fecha_idx"
            ),
        ),
    ]
