# Generated by Django 6.0.3 on 2026-04-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_add_asistencia_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="dni",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="profesor",
            name="dni",
            field=models.CharField(max_length=15),
        ),
    ]
