# Generated by Django 6.0.3 on 2026-04-09 03:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_dni_alphanumeric_15chars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matricula",
            name="fecha_matricula",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
