# Generated by Django 6.0.3 on 2026-04-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_make_fecha_matricula_editable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preciopaquete",
            name="cantidad_clases",
            field=models.IntegerField(verbose_name="Cantidad de Clases"),
        ),
        migrations.AlterField(
            model_name="preciopaquete",
            name="cantidad_clases_secundaria",
            field=models.IntegerField(
                blank=True,
                help_text="Solo para combo_musical y mixto. Ej: combo 12+8 → principal=12, secundaria=8",
                null=True,
                verbose_name="Cantidad de Clases Secundaria",
            ),
        ),
        migrations.AlterField(
            model_name="recibo",
            name="paquete_aplicado",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("combo_musical_12", "Combo Musical 12+12"),
                    ("combo_musical_8", "Combo Musical 8+8"),
                    ("combo_musical_12_8", "Combo Musical 12+8"),
                    ("combo_musical_8_8", "Combo Musical 8+8 (otro)"),
                    ("combo_musical_12_12", "Combo Musical 12+12 (otro)"),
                    ("mixto_12", "Mixto 12+12"),
                    ("mixto_8", "Mixto 8+8"),
                    ("mixto_12_8", "Mixto 12+8"),
                    ("mixto_8_8", "Mixto 8+8 (otro)"),
                    ("mixto_12_12", "Mixto 12+12 (otro)"),
                    ("intensivo_instrumento", "Intensivo Instrumento"),
                    ("intensivo_taller", "Intensivo Taller"),
                ],
                default="individual",
                max_length=30,
                verbose_name="Paquete promocional aplicado",
            ),
        ),
    ]
