# Generated by Django 6.0.3 on 2026-06-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_cantidad_clases_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoraTrabajada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("clase_regular", "Clase Regular"),
                            ("asistencia", "Asistencia"),
                            ("hora_extra", "Hora Extra"),
                            ("clase_cancelada", "Clase Cancelada"),
                        ],
                        default="clase_regular",
                        max_length=20,
                    ),
                ),
                (
                    "horas_trabajadas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("num_alumnos", models.PositiveIntegerField(default=0)),
                (
                    "valor_generado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "monto_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "monto_adicional",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "monto_profesor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ganancia_taller",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("config_snapshot", models.JSONField(blank=True, null=True)),
                ("observacion", models.TextField(blank=True)),
                (
                    "created_from",
                    models.CharField(
                        choices=[
                            ("asistencia_auto", "Asistencia Auto"),
                            ("admin_manual", "Admin Manual"),
                        ],
                        default="admin_manual",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horas_trabajadas",
                        to="core.ciclo",
                    ),
                ),
                (
                    "horario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="horas_trabajadas",
                        to="core.horario",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horas_trabajadas",
                        to="core.profesor",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(fields=["fecha"], name="ht_fecha_idx"),
                    models.Index(
                        fields=["profesor", "fecha"], name="ht_profesor_fecha_idx"
                    ),
                    models.Index(
                        fields=["ciclo", "profesor", "estado", "fecha"],
                        name="ht_ciclo_prof_estado_fecha_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("horario__isnull", False)),
                        fields=("profesor", "horario", "fecha", "tipo"),
                        name="uq_hora_trabajada_profesor_horario_fecha_tipo",
                    )
                ],
            },
        ),
    ]
