# Generated by Django 5.2.15 on 2026-06-14 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_notaclase"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaDia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("contenido", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_dia",
                        to="core.ciclo",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_dia",
                        to="core.profesor",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(
                        fields=["ciclo", "fecha"], name="core_notadi_ciclo_i_20f91b_idx"
                    )
                ],
                "unique_together": {("ciclo", "profesor", "fecha")},
            },
        ),
    ]
