# Generated by Django 5.2.15 on 2026-06-14 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_notadia"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaAlumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("contenido", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_alumno",
                        to="core.alumno",
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_alumno",
                        to="core.ciclo",
                    ),
                ),
                (
                    "horario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_alumno",
                        to="core.horario",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_alumno",
                        to="core.profesor",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(
                        fields=["horario", "fecha"],
                        name="core_notaal_horario_6317e9_idx",
                    )
                ],
                "unique_together": {("profesor", "horario", "alumno", "fecha")},
            },
        ),
    ]
