# Generated by Django 5.2.15 on 2026-06-23 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_notaalumno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recibo",
            name="alumno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recibos",
                to="core.alumno",
                verbose_name="Alumno principal (opcional)",
            ),
        ),
        migrations.AlterField(
            model_name="recibo",
            name="ciclo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recibos",
                to="core.ciclo",
            ),
        ),
        migrations.AlterField(
            model_name="recibomatricula",
            name="matricula",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recibos",
                to="core.matricula",
            ),
        ),
    ]
