# Generated by Django 5.2.15 on 2026-06-23 19:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_recibo_alumno_alter_recibo_ciclo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="egreso",
            name="monto",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
