# Generated by Django 5.2.15 on 2026-06-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_egreso_monto"),
    ]

    operations = [
        migrations.AddField(
            model_name="recibo",
            name="metodo_pago",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("transferencia", "Transferencia"),
                    ("tarjeta", "Tarjeta"),
                    ("yape", "Yape"),
                    ("plin", "Plin"),
                    ("otro", "Otro"),
                ],
                default="efectivo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="horatrabajada",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("aprobada", "Aprobada"),
                    ("rechazada", "Rechazada"),
                ],
                default="aprobada",
                max_length=20,
            ),
        ),
    ]
