# Generated by Django 5.2.15 on 2026-07-25 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_add_metodo_pago_recibo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feriado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("motivo", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feriados",
                        to="core.ciclo",
                    ),
                ),
                (
                    "horario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feriados",
                        to="core.horario",
                    ),
                ),
                (
                    "taller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feriados",
                        to="core.taller",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("taller__isnull", False),
                            ("horario__isnull", False),
                            _connector="OR",
                        ),
                        fields=("ciclo", "fecha", "taller", "horario"),
                        name="unique_feriado_per_scope",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("horario__isnull", True), ("taller__isnull", True)
                        ),
                        fields=("ciclo", "fecha"),
                        name="unique_global_feriado",
                    ),
                ],
            },
        ),
    ]
