# Generated by Django 5.2.15 on 2026-07-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_feriado"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="feriado",
            name="unique_feriado_per_scope",
        ),
        migrations.AddConstraint(
            model_name="feriado",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("horario__isnull", True), ("taller__isnull", False)
                ),
                fields=("ciclo", "fecha", "taller"),
                name="unique_taller_feriado",
            ),
        ),
        migrations.AddConstraint(
            model_name="feriado",
            constraint=models.UniqueConstraint(
                condition=models.Q(("horario__isnull", False)),
                fields=("ciclo", "fecha", "horario"),
                name="unique_horario_feriado",
            ),
        ),
    ]
