# Generated by Django 5.2.15 on 2026-07-27 03:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_feriado_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracion",
            name="ciclo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configuracion_pago",
                to="core.ciclo",
            ),
        ),
        migrations.AddField(
            model_name="configuracion",
            name="porcentaje_adicional",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.50"),
                max_digits=5,
                verbose_name="Porcentaje adicional",
            ),
        ),
        migrations.AddConstraint(
            model_name="configuracion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ciclo__isnull", False)),
                fields=("ciclo",),
                name="unique_ciclo_config",
            ),
        ),
    ]
