# Generated by Django 5.2.15 on 2026-07-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_agregar_ciclo_configuracion_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="feriado",
            name="grupo",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
