# Generated by Django 5.2.15 on 2026-07-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_add_grupo_to_feriado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recibo",
            name="fecha_emision",
            field=models.DateField(db_index=True),
        ),
    ]
