# Generated by Django 5.2.15 on 2026-07-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_add_fecha_emision_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recibo",
            name="paquete_aplicado",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Paquete promocional aplicado",
            ),
        ),
    ]
