# Generated by Django 5.2.15 on 2026-07-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_nota"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="asistencia",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="preciopaquete",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="asistencia",
            constraint=models.UniqueConstraint(
                condition=models.Q(("matricula__isnull", False)),
                fields=("matricula", "horario", "fecha"),
                name="unique_asistencia_matricula_horario_fecha",
            ),
        ),
        migrations.AddConstraint(
            model_name="preciopaquete",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ciclo__isnull", False)),
                fields=(
                    "ciclo",
                    "tipo_taller",
                    "tipo_paquete",
                    "cantidad_clases",
                    "cantidad_clases_secundaria",
                ),
                name="unique_precio_ciclo",
            ),
        ),
        migrations.AddConstraint(
            model_name="preciopaquete",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ciclo__isnull", True)),
                fields=(
                    "tipo_taller",
                    "tipo_paquete",
                    "cantidad_clases",
                    "cantidad_clases_secundaria",
                ),
                name="unique_precio_global",
            ),
        ),
    ]
