# Generated by Django 5.2.15 on 2026-08-01 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_alter_asistencia_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notadia",
            options={"ordering": ["-fecha", "-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="notadia",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="notadia",
            name="titulo",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="notadia",
            name="ciclo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notas_generales",
                to="core.ciclo",
            ),
        ),
        migrations.AlterField(
            model_name="notadia",
            name="profesor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notas_generales",
                to="core.profesor",
            ),
        ),
        migrations.AddIndex(
            model_name="notadia",
            index=models.Index(
                fields=["profesor", "fecha"], name="core_notadi_profeso_fb0911_idx"
            ),
        ),
    ]
